import type { Severity } from "../checker/framework/types.js";

export const SCAN_PROFILES: Record<string, Record<string, Severity | "off">> = {
  strict: {},
  "exports-only": {
    "types/false-cjs-esm": "off",
    "types/false-export-default": "off",
    "types/missing-export-equals": "off",
    "types/esm-dynamic-only": "off",
    "types/resolution": "off",
    "files/sensitive": "off",
    "files/bin-executable": "off",
    "files/bin-shebang": "off",
    "files/duplicate-dep": "off",
    "files/files-field": "off",
    "files/format-validation": "off",
    "files/local-dependency": "off",
    "files/prepublish": "off",
    "metadata/license": "off",
    "metadata/license-file": "off",
    "metadata/engines": "off",
    "metadata/repository": "off",
    "metadata/repository-format": "off",
    "metadata/deprecated-fields": "off",
    "metadata/peer-dep-conflict": "off",
    "metadata/side-effects": "off",
    "size/package-size": "off",
  },
  "types-only": {
    "exports/type-module": "off",
    "exports/exports-field": "off",
    "exports/dot-entry": "off",
    "exports/types-order": "off",
    "exports/import-condition": "off",
    "exports/file-exists": "off",
    "exports/value-invalid": "off",
    "exports/default-last": "off",
    "exports/module-before-require": "off",
    "exports/format-mismatch": "off",
    "exports/types-format": "off",
    "exports/no-deprecated-subpath-mapping": "off",
    "exports/browser-conflict": "off",
    "exports/types-first": "off",
    "exports/esm-main-no-exports": "off",
    "exports/module-no-exports": "off",
    "exports/types-not-exported": "off",
    "exports/file-not-published": "off",
    "exports/glob-matched-files": "off",
    "files/sensitive": "off",
    "files/bin-executable": "off",
    "files/bin-shebang": "off",
    "files/duplicate-dep": "off",
    "files/files-field": "off",
    "files/format-validation": "off",
    "files/local-dependency": "off",
    "files/prepublish": "off",
    "metadata/license": "off",
    "metadata/license-file": "off",
    "metadata/engines": "off",
    "metadata/repository": "off",
    "metadata/repository-format": "off",
    "metadata/deprecated-fields": "off",
    "metadata/peer-dep-conflict": "off",
    "metadata/side-effects": "off",
    "size/package-size": "off",
  },
};
